"""
services/pdf_service.py
------------------------
AI Feature 4: AI Referral PDF. Builds a professional referral summary
PDF for a mother's High/Critical assessment using reportlab.
"""

from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_referral_pdf(mother: dict, assessment: dict, referral: dict, ai_summary: str | None = None) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title2", parent=styles["Title"], textColor=colors.HexColor("#0B1220"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#22364F"))
    body = styles["BodyText"]

    story = [
        Paragraph("CareNest AI — Maternal Referral Summary", title_style),
        Spacer(1, 0.3 * cm),
        Paragraph("AI-Powered Maternal &amp; Child Health Platform · Prototype output — not a diagnosis.", body),
        Spacer(1, 0.6 * cm),
    ]
    if ai_summary:
        story += [
            Paragraph("AI Summary", h2),
            Paragraph(ai_summary, body),
            Spacer(1, 0.5 * cm),
        ]
    story += [
        Paragraph("Mother Details", h2),
        Table([
            ["Name", mother["name"]],
            ["Age", str(mother["age"])],
            ["Village", mother["village"]],
            ["Phone", mother.get("phone", "—")],
            ["Pregnancy Week", str(assessment.get("week", "—"))],
        ], colWidths=[4 * cm, 10 * cm], style=TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#0B1220")),
        ])),
        Spacer(1, 0.5 * cm),
        Paragraph("AI Risk Assessment", h2),
        Paragraph(f"<b>Risk Level:</b> {assessment['risk_level']} &nbsp;&nbsp; "
                  f"<b>Score:</b> {assessment['risk_score']}/100", body),
        Spacer(1, 0.2 * cm),
        Paragraph("<b>Reasons (AI-generated, rule-based &amp; explainable):</b>", body),
    ]
    for reason in assessment.get("risk_factors", []):
        story.append(Paragraph(f"• {reason}", body))

    story += [
        Spacer(1, 0.4 * cm),
        Paragraph("Referral", h2),
        Paragraph(f"<b>Recommended Facility:</b> {referral['recommended_facility']}", body),
        Paragraph(f"<b>Urgency:</b> {referral['urgency']}", body),
        Paragraph(f"<b>Status:</b> {referral['status']}", body),
        Spacer(1, 0.4 * cm),
        Paragraph("Recommendation", h2),
        Paragraph(assessment.get("recommendation", "—"), body),
        Spacer(1, 0.8 * cm),
        Paragraph(
            "This document is generated by an explainable, rule-based screening model as part of a "
            "hackathon prototype. It is a decision-support aid only and does not replace clinical judgement.",
            styles["Italic"],
        ),
    ]

    doc.build(story)
    return buf.getvalue()
